(function(){
  'use strict';
  const $=(id)=>document.getElementById(id); const tokenKey='orbit-admin-token'; let token=localStorage.getItem(tokenKey)||''; let admin=null; let data={users:[],reviews:[],announcements:[],levels:[]}; let reviewFilter='pending'; let toastTimer=0;
  const escapeText=(value)=>String(value||'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(message){clearTimeout(toastTimer);$('adminToast').textContent=message;$('adminToast').classList.remove('hidden');toastTimer=setTimeout(()=>$('adminToast').classList.add('hidden'),2800)}
  async function api(url,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${token}`};const response=await fetch(url,{...options,headers});let result={};try{result=await response.json()}catch{}if(response.status===401){token='';localStorage.removeItem(tokenKey);$('adminLogin').classList.remove('hidden')}if(!response.ok)throw new Error(result.message||result.error||'请求失败');return result}
  function switchView(name){document.querySelectorAll('[data-view]').forEach((b)=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.admin-view').forEach((p)=>p.classList.toggle('active',p.dataset.panel===name));$('viewTitle').textContent={overview:'运营总览',reviews:'关卡审核',users:'创作者管理',announcements:'公告中心',levels:'公开星图'}[name]||'星环控制台'}
  async function load(){try{data=await api('/api/admin/dashboard');render()}catch(error){toast(error.message)}}
  function render(){const pending=data.reviews.filter((r)=>r.status==='pending').length;const creators=data.users.filter((u)=>u.role==='creator').length;$('statPending').textContent=pending;$('statCreators').textContent=creators;$('statLevels').textContent=data.levels.length;$('statAnnouncements').textContent=data.announcements.length;$('reviewBadge').textContent=pending;renderRecent();renderReviews();renderUsers();renderAnnouncements();renderLevels()}
  function renderRecent(){const rows=data.reviews.slice(0,5);$('recentReviews').innerHTML=rows.length?rows.map((r)=>`<div class="compact-row"><b>${escapeText(r.level.planetName)}</b><span>${escapeText(r.creatorAccount)} · ${new Date(r.createdAt).toLocaleDateString('zh-CN')}</span><em>${{pending:'待审核',approved:'已通过',rejected:'已拒绝'}[r.status]}</em></div>`).join(''):'<p>暂无审核申请。</p>'}
  function renderReviews(){const rows=data.reviews.filter((r)=>reviewFilter==='all'||r.status===reviewFilter);const grid=$('reviewGrid');if(!rows.length){grid.innerHTML='<section class="ops-panel"><p>当前筛选条件下没有审核单。</p></section>';return}grid.innerHTML=rows.map((r)=>{const clips=(r.level.phases||[]).reduce((sum,p)=>sum+(p.tracks||[]).reduce((s,t)=>s+(t.clips||[]).length,0),0);const status={pending:'待审核',approved:'已通过',rejected:'已拒绝'}[r.status];return `<article class="review-card" data-review="${r.id}"><header><div><span>${escapeText(r.creatorAccount)} // ${new Date(r.createdAt).toLocaleDateString('zh-CN')}</span><h3>${escapeText(r.level.planetName)}</h3></div><em class="${r.status}">${status}</em></header><p>${escapeText(r.level.description)}</p><div class="review-meta"><div><span>阶段</span><b>${r.level.phases?.length||1}</b></div><div><span>片段</span><b>${clips}</b></div><div><span>难度</span><b>LV.${r.level.difficulty}</b></div></div><textarea class="review-note" placeholder="通过备注或拒绝原因">${escapeText(r.reason||'')}</textarea><div class="review-actions"><button data-action="preview">▶ 试玩</button><button class="approve" data-action="approve">通过</button><button class="reject" data-action="reject">拒绝</button></div></article>`}).join('');grid.querySelectorAll('[data-action]').forEach((button)=>button.addEventListener('click',()=>reviewAction(button.closest('[data-review]'),button.dataset.action)))}
  async function reviewAction(card,action){const id=card.dataset.review;const note=card.querySelector('.review-note').value.trim();try{if(action==='preview'){const result=await api(`/api/admin/reviews/${id}/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});window.open(result.playUrl,'_blank','noopener');return}if(action==='reject'&&!note)return toast('拒绝时需要填写修改原因');await api(`/api/admin/reviews/${id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='reject'?{reason:note}:{note})});toast(action==='approve'?'关卡已通过并发布到星图':'已拒绝并通知创作者');await load()}catch(error){toast(error.message)}}
  function renderUsers(){const rows=data.users.filter((u)=>u.role==='creator');$('userTable').innerHTML=rows.length?rows.map((u)=>`<div class="table-row" data-user="${u.id}"><b>${escapeText(u.displayName)}</b><span>${escapeText(u.account)}</span><em class="${u.active?'':'disabled'}">${u.active?'启用':'已停用'}</em><time>${u.disabledAt?`停用于 ${new Date(u.disabledAt).toLocaleDateString('zh-CN')}`:new Date(u.createdAt).toLocaleDateString('zh-CN')}</time><div class="row-actions"><button type="button" data-action="reset">重置密码</button><button type="button" data-action="toggle">${u.active?'停用账号':'恢复账号'}</button></div></div>`).join(''):'<p>暂无创作者账号。</p>';$('userTable').querySelectorAll('button').forEach((button)=>button.addEventListener('click',async()=>{const row=button.closest('[data-user]');const user=rows.find((u)=>u.id===row.dataset.user);let payload={active:!user.active};if(button.dataset.action==='reset'){const password=prompt(`为 ${user.account} 设置新密码（至少 8 位）`);if(password===null)return;payload={newPassword:password}}else if(user.active&&!confirm(`确认停用 ${user.account}？该账号的现有工坊会话会立即失效。`))return;try{const result=await api(`/api/admin/users/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});Object.assign(user,result.user);renderUsers();toast(button.dataset.action==='reset'?'密码已重置':result.user.active?'账号已恢复':'账号已停用，现有会话已强制退出');await load()}catch(error){toast(error.message)}}))}
  function renderAnnouncements(){$('announcementList').innerHTML=data.announcements.length?data.announcements.map((a)=>`<article class="announcement-item" data-announcement="${a.id}"><b>${escapeText(a.title)}</b><p>${escapeText(a.body)}</p><time>${new Date(a.createdAt).toLocaleString('zh-CN')} · ${escapeText(a.author)}</time><button type="button">删除</button></article>`).join(''):'<p>还没有发布公告。</p>';$('announcementList').querySelectorAll('button').forEach((button)=>button.addEventListener('click',async()=>{if(!confirm('确认删除这条公告？'))return;try{await api(`/api/admin/announcements/${button.closest('[data-announcement]').dataset.announcement}`,{method:'DELETE'});toast('公告已删除');await load()}catch(error){toast(error.message)}}))}
  function renderLevels(){$('levelTable').innerHTML=data.levels.length?data.levels.map((l)=>`<div class="table-row" data-level="${l.id}"><b>${escapeText(l.planetName)}</b><span>${escapeText(l.author)}</span><span>${l.phaseCount} 阶段</span><a href="${l.playUrl}" target="_blank" rel="noopener">试玩</a><button type="button">下架</button></div>`).join(''):'<p>公开星图暂时为空。</p>';$('levelTable').querySelectorAll('button').forEach((button)=>button.addEventListener('click',async()=>{if(!confirm('确认从公开星图下架这个关卡？'))return;try{await api(`/api/admin/levels/${button.closest('[data-level]').dataset.level}`,{method:'DELETE'});toast('关卡已下架');await load()}catch(error){toast(error.message)}}))}
  document.querySelectorAll('[data-view]').forEach((b)=>b.addEventListener('click',()=>switchView(b.dataset.view)));document.querySelectorAll('[data-jump]').forEach((b)=>b.addEventListener('click',()=>switchView(b.dataset.jump)));document.querySelectorAll('[data-review-filter]').forEach((b)=>b.addEventListener('click',()=>{reviewFilter=b.dataset.reviewFilter;document.querySelectorAll('[data-review-filter]').forEach((i)=>i.classList.toggle('active',i===b));renderReviews()}));
  $('refreshBtn').addEventListener('click',load);$('logoutBtn').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}token='';localStorage.removeItem(tokenKey);$('adminLogin').classList.remove('hidden')});
  $('createUserForm').addEventListener('submit',async(event)=>{event.preventDefault();try{await api('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account:$('newAccount').value,displayName:$('newDisplayName').value,password:$('newPassword').value})});event.target.reset();toast('创作者账号已创建');await load()}catch(error){toast(error.message)}});
  $('announcementForm').addEventListener('submit',async(event)=>{event.preventDefault();try{await api('/api/admin/announcements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('announcementTitle').value,body:$('announcementBody').value})});event.target.reset();toast('公告已发布到游戏邮箱');await load()}catch(error){toast(error.message)}});
  $('adminLoginForm').addEventListener('submit',async(event)=>{event.preventDefault();$('loginError').classList.add('hidden');try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account:$('adminAccount').value,password:$('adminPassword').value})});const result=await response.json();if(!response.ok)throw new Error(result.message||'登录失败');if(result.user.role!=='admin')throw new Error('该账号没有管理员权限');token=result.token;admin=result.user;localStorage.setItem(tokenKey,token);$('adminName').textContent=admin.displayName;$('adminLogin').classList.add('hidden');await load()}catch(error){$('loginError').textContent=error.message;$('loginError').classList.remove('hidden')}});
  async function boot(){if(token){try{const result=await api('/api/auth/me');if(result.user.role!=='admin')throw new Error('没有管理员权限');admin=result.user;$('adminName').textContent=admin.displayName;$('adminLogin').classList.add('hidden');await load();return}catch{token='';localStorage.removeItem(tokenKey)}}$('adminLogin').classList.remove('hidden')}
  setInterval(()=>{$('serverTime').textContent=new Date().toLocaleString('zh-CN')},1000);boot();
})();
